### ISSUE TITLE
Question: fly_app deprecation?

### ISSUE THREAD

**Issue by jonahgeorge** [fly-apps/terraform-provider-fly#100]
The README currently states that Fly apps will be deprecated soon. Is that hidden knowledge of the Fly platform or a choice to deprecate them from this provider?

I ask as Fly Machines appear to have some increased complexity for those of us that want simple application management (particularly around auto-migration on hardware failure):
https://fly.io/blog/fly-machines/#how-fly-machines-will-frustrate-you-the-emotional-cost-of-simplicity

Happy to ask on the Fly forum instead, but this is the only mention of app deprecation I've been able to find. If it is just in the provider, is there a reason for it?

Thanks a ton for your work on this. Just hoping to get some increased clarity :)

**Comment by DAlperin** [comment]
@jonahgeorge ah yeah I probably have to write a better explanation. Fly apps as they exist today, our PAAS offering, a-la heroku will be rebuilt on machines. The terraform provider for directly provisioning resources, like machines. This is a distinction we are not yet good at explaining. I'm going to close this but please just reply if you have more questions, I am happy to answer them.

**Comment by jonahgeorge** [comment]
Makes sense! In that case will the limitations identified in the blog post be eliminated at some point in the future? Or will the PAAS offering seamlessly migrate onto machines, if it hasn't already? If the latter, will this provider be updated to include resources for managing the PAAS-related objects?

The context of my questions comes from a desire to manage Heroku-like apps in Terraform. Trying to determine what risk I have from using machines in the provider now vs what a future state might look like.

**Comment by jonahgeorge** [comment]
@DAlperin kind nudge -- just curious about whether I should be requesting/adding additional fields to the fly_app resource to accomplish what I'm after.
