### ISSUE TITLE
CockroachDB 

### ISSUE THREAD

**Issue by gedw99** [fly-apps/terraform-provider-fly#156]
I was wondering if there is a likelihood that the postresql equivalent called cockroachdb might be supported ?

https://github.com/cockroachdb/terraform-provider-cockroach

my uses case is that I was using postresql but need to change to cockroachdb so I can use their change feeds.

I know that with the changeover to Fly Machines there is much flux. 

I just wanted to know what blockers thee are so that I could know the extend of the effort .

**Comment by zxaos** [comment]
It's unlikely we're going to support cockroachdb (or other dbs) directly in the terraform provider at this time.

However it's possible to deploy cockroachdb as a regular fly app. There's [some discussion in our community forums about how to deploy CockroachDB successfully](https://community.fly.io/t/cockroachdb-on-fly-io/1650), and you'll definitely hit a wider pool of support for working through that setup there than here.
