### ISSUE TITLE
Add option to force a request trace in Fly instrumentation tools

### ISSUE THREAD

**Issue by jsierles** [fly-apps/terraform-provider-fly#16]
Graphql accepts the `Fly-Force-Trace` header. The REST API may support this later.

**Comment by jsierles** [comment]
I think provider-wide, but off by default. Using this option should also output a useful warning so people don't leave it on all the time. We may also want to display debug info like the `Fly-Request-ID` returned from the API.

**Comment by DAlperin** [comment]
Would an environment variable do? FLY_DEVELOPER_MODE or some such?

**Comment by jsierles** [comment]
`DEBUG` would be good!
