### ISSUE TITLE
Machine names can't be mutated

### ISSUE THREAD

**Issue by jsierles** [fly-apps/terraform-provider-fly#19]
Changing a machine name should trigger a recreate.

**Comment by DAlperin** [comment]
On second thought, are we ok with letting the provider automatically destroy resources without intervention?

**Comment by jsierles** [comment]
Having to confirm a destroy seems like a good enough barrier, if that's what you mean.

**Comment by hb9cwp** [comment]
While testing with Terraform v1.2.2 and TF plugin for Fly v0.0.6 with remote .tfstate in a Workspace on Terraform Cloud and GitHub as CI/CD pipeline, I also stumbled over this. My implicit expectation was that a change the app/machine's name, the existing one `fly-gohttps-03` below will be destroyed, including all its resources (IPs, Cert), and then a new one `-04` will be created with all new resources:
 
> Error: Can't mutate Name of existing app
> with fly_app.flyGoHTTPS
> on flyGoHTTPS.tf line 49, in resource "fly_app" "flyGoHTTPS":
> resource "fly_app" "flyGoHTTPS" {
> Can't switch name fly-gohttps-03 to fly-gohttps-04

To clean up the situation, I ended up destroying the machine `-03` on Fly manually, and removing the remote state using `terraform rm ...`.

**Comment by DAlperin** [comment]
@hb9cwp Yeah, this was fixed in https://github.com/fly-apps/terraform-provider-fly/commit/f9c2cfb802a4777b51c0416adee41ec7fb2000ae but has not made it into a released version. I'll cut a 0.0.7 release tomorrow that has a lot of fixes from this last week.

**Comment by OJFord** [comment]
This also (to date) affects `fly_app` - do you want a separate issue for it @DAlperin?
