### ISSUE TITLE
Build images

### ISSUE THREAD

**Issue by hb9cwp** [fly-apps/terraform-provider-fly#24]
Is there already a way in this TF provider v0.0.6 to trigger the build host to (re-)build images [from Dockerfiles (and from Buildpacks as the other option)](https://fly.io/docs/reference/builders/), similar to what `flyctl launch/deploy` do, which can thereafter be started as machines (from the private registry)? Thanks.

**Comment by DAlperin** [comment]
Hmmm. This is a good question. This feels doable. I can try that this week. I have been stuck on a TF bug for a few days so I haven't been able to add new stuff but I think I'm gonna put that one away for now.

**Comment by ximus** [comment]
thanks @DAlperin. Taking care of docker builds separately is fine and makes sense. 

I have a question. 

Given `image` is a required attribute of `machine`, this strongly encourages using terraform as the app deployment tool as well as the infrastructure management tool right?

If my app is versioned and each version has a docker image. Then I need to always apply terraform with the current version of my app as a variable to reference the correct current image. At which point, might as well just use terraform to deploy, t? 

Note that I could use a generic "latest" image tag to avoid passing a version but such wildcard tags are not recommended if I'm not mistaken.

This seems fine to me, but am I understanding things correctly? Sorry I'm not a seasoned devops and can be rusty. Also, new to fly.

**Comment by DAlperin** [comment]
I, too, am not a seasoned Devops person, so take what I say with a grain of salt. But yeah! That sounds like a totally reasonable way to do things.
