### ISSUE TITLE
If not maintained nor recommended, what is?

### ISSUE THREAD

**Issue by antgel** [fly-apps/terraform-provider-fly#254]
I'm new here and just saw #253 which doesn't bode well. There was no discussion around that PR, so there's no *why*; if this provider is not maintained nor recommended as a way to deploy to fly.io, what is? (For organizations who want to manage their infrastructure with IaC.) @catflydotio

**Comment by catflydotio** [comment]
Hi @antgel, it's not a satisfying answer, but we don't have an IaC story yet, so we recommend first-party tooling: flyctl and/or the Machines API.

More detail: https://community.fly.io/t/fresh-produce-volumes-endpoints-in-machines-api/14408/16
