### ISSUE TITLE
GraphQL client schema mismatch for $addrType

### ISSUE THREAD

**Issue by vincecima** [fly-apps/terraform-provider-fly#35]
I am using v0.0.9 of the provider and attempting to allocate a v4 IP address for my app. Here is an example of what the TForm looks like

```hcl
resource "fly_app" "production" {
  name = "site-production"
}

resource "fly_ip" "exampleIp" {
  app  = "site-production"
  type = "v4"
}
```

When running `terraform apply` I was consistently hitting the following error:

```
input:3: mutation AllocateIpAddress.allocateIpAddress.input.type Nullability mismatch on variable $addrType and argument type (IPAddressType /
│ IPAddressType!)
```

I dug into the source and it seems like the GraphQL schema has changed since the last time the provider was released. I put together a PR that includes an update to the GraphQL client, the changed code does seem to fix the issue https://github.com/fly-apps/terraform-provider-fly/pull/34.

I am a newcomer to go and GraphQL in general. It looks like my PR includes some potentially unwanted changes. Can you help document the correct way to update the client?

Thanks!

**Comment by DAlperin** [comment]
@vincecima sorry I didn't see this until now. I have been busy working on some stuff unrelated to terraform directly this last week. The PR is great, the extra noise you are seeing is just go modules doing it's thing. It's usually fine to ignore.

I'll cut a new release tomorrow and you can give it a go and make sure it fixes everything.

I will also try and add some tests for all the resources to catch regressions like this.

**Comment by vincecima** [comment]
Thanks @DAlperin,

One thing you might want to look into before cutting a new release is the removal of comments from graphql/generated.go.

**Comment by DAlperin** [comment]
@vincecima v0.0.10 is out. The comments in the generated.go file are the ones that are automatically created by genqlient so I don't really mind leaving it alone.

**Comment by DAlperin** [comment]
Let me know once you get a chance to try out `0.0.10` so we can close out this issue! :)

**Comment by vincecima** [comment]
@DAlperin 

Ok, bumped the version to `0.0.10` and everything looks good. I was able to destroy and recreate IP addresses without issue. Thanks!
