### ISSUE TITLE
Cannot create machine without services

### ISSUE THREAD

**Issue by mochja** [fly-apps/terraform-provider-fly#46]
It seems that services property cannot be set to null and going around with setting to empty list will fail when data are received back as the response does not contain the services property.

```
+ resource "fly_machine" "machine" {
      + ...
      + services = [
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.

fly_machine.machine["fra"]: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to fly_machine.machine["fra"], provider
│ "provider[\"registry.terraform.io/fly-apps/fly\"]" produced an unexpected new value: .services: was
│ cty.ListValEmpty(cty.Object(map[string]cty.Type{"internal_port":cty.Number,
│ "ports":cty.List(cty.Object(map[string]cty.Type{"handlers":cty.List(cty.String), "port":cty.Number})),
│ "protocol":cty.String})), but now null.
```

Plan above actually creates new resource, but cannot store it into the tf state.

I can create machine without services trough API.

I think services property on `fly_machine` resource could be _optional_.

**Comment by DAlperin** [comment]
Ran into this one myself yesterday as well. I think I'll retool some things to make services optional.
