### ISSUE TITLE
fly_app data query fails with a type mismatch between struct and object

### ISSUE THREAD

**Issue by jbcom** [fly-apps/terraform-provider-fly#91]
I'm running into an interesting error. I have some workspaces that haven't been exercised in awhile (0.0.10 ~ 0.0.19) and am running up against:

│ Error: Value Conversion Error
│
│   with module.base.data.fly_app.existing[0],
│ An unexpected error was encountered trying to convert tftypes.Value into
│ provider.appDataSourceOutput. This is always an error in the provider. Please
│ report the following to the provider developer:
│
│ mismatch between struct and object: Struct defines fields not found in
│ object: secrets.
╵

There does not appear to be anything additional in the debug logs that would be helpful, however if y'all need anything just ask. It occurs 100% of the time.

I'm running it on MacOS 12.6 against Terraform v1.2.4.

**Comment by DAlperin** [comment]
Ohhh oops I checked in some WIP code into a release accidentally! That's not good. Sorry about that! I'll release an update soon.

**Comment by jbcom** [comment]
> Ohhh oops I checked in some WIP code into a release accidentally! That's not good. Sorry about that! I'll release an update soon.

You're an absolute rock star. Thanks for the quick response. Any chance I could get a rough ETA since it's not going to require dev time? Would be great to be able to communicate outwardly to teams depending on this for some launches. 🙇

**Comment by DAlperin** [comment]
@jbcom v0.0.20 is releasing now. That should solve the problem https://github.com/fly-apps/terraform-provider-fly/actions/runs/3206356480

**Comment by DAlperin** [comment]
@jbcom let me know if v0.0.20 fixes it
